package com.atlassian.plugins.codegen.modules.confluence.blueprint;

import com.atlassian.plugins.codegen.AbstractModuleCreatorTestCase;
import com.atlassian.plugins.codegen.PluginProjectChangeset;
import com.atlassian.plugins.codegen.modules.common.Resource;
import com.atlassian.plugins.codegen.modules.common.web.WebItemProperties;
import com.google.common.collect.Lists;
import org.dom4j.Element;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.util.List;

import static com.atlassian.plugins.codegen.modules.confluence.blueprint.BlueprintProperties.INDEX_KEY;
import static com.atlassian.plugins.codegen.modules.confluence.blueprint.BlueprintProperties.WEB_ITEM_BLUEPRINT_KEY;
import static org.junit.Assert.assertEquals;

/**
 * @since 4.1.7
 */
public class BlueprintCreatorTest extends AbstractModuleCreatorTestCase<BlueprintProperties>
{
    // The Properties under test
    private BlueprintProperties blueprintProps;

    // The expected values for the Properties and created plugin content
    private String blueprintModuleKey;
    private String blueprintModuleName;
    private String blueprintIndexKey;
    private String webItemName;
    private String webItemDesc;
    private String templateModuleKey;
    private String templateNameI18nKey;
    private String templateName;
    private String templateDescI18nKey;
    private String templateDesc;
    private String templateResourceName = "template";
    private String templateResourceType = "download";
    private String templateResourceLocation;
    private String webItemModuleKey;
    private String webItemNameI18nKey;
    private String webItemDescI18nKey;
    private String webItemResourceName = "icon";
    private String webItemResourceType = "download";
    private String webItemResourceLocation;
    private String webItemSection;

    public BlueprintCreatorTest()
    {
        super("blueprint", new BlueprintModuleCreator());
    }

    @Before
    public void setupProps() throws Exception
    {
        blueprintProps = new BlueprintProperties();
        setProps(blueprintProps);
    }

    @After
    public void tearDown()
    {
        changeset = null;
    }

    // Not sure why the changeset isn't always being cached during the test? Pull request comment pleez :) dT
    @Override
    protected PluginProjectChangeset getChangesetForModule() throws Exception
    {
        if (changeset == null)
        {
            changeset = super.getChangesetForModule();
        }
        return changeset;
    }

    @Test
    public void basicWiringIsAdded() throws Exception
    {
        // Set up properties generated by the BlueprintPrompter. Note that some are user-entered and some are
        // generated by the prompter, so the prompter will need Unit tests confirming that each of these values is set
        // in the BlueprintProperties correctly.
        blueprintModuleKey = "foo-print-blueprint";
        blueprintModuleName = "FooPrint Blueprint";
        blueprintIndexKey = "foo-print";

        // TODO - Check for these in the i18n props
        webItemName = "FooPrint";
        webItemDesc = "There's no Blueprint like my FooPrint.";

        templateModuleKey = "foo-plate";
        templateNameI18nKey = "template.name.i18n.key";
        templateName = "FooPrint Content Template 0"; // generated
        templateDescI18nKey = "template.desc.i18n.key";
        templateDesc = "Contains Storage-format XML used by the FooPrint Blueprint";
        templateResourceLocation = "my/template/path";

        webItemModuleKey = "foo-print-item";
        webItemNameI18nKey = "foo-print-blueprint.display.name.i18n.key";
        webItemDescI18nKey = "foo-print-blueprint.display.desc.i18n.key";
        webItemSection = "system.create.dialog/content";
        webItemResourceLocation = "my/web-item/icon/path";

        blueprintProps.setModuleKey(blueprintModuleKey);
        blueprintProps.setModuleName(blueprintModuleName);
        blueprintProps.setProperty(INDEX_KEY, blueprintIndexKey);
        blueprintProps.setWebItem(makeWebItemProperties());
        blueprintProps.addContentTemplate(makeContentTemplateProperties());

        // CREATE!
        getChangesetForModule();

        assertAtlassianPluginXmlCorrect();

        // Check i18n properties in the file
        assertI18nString(webItemNameI18nKey, webItemName);
        assertI18nString(webItemDescI18nKey, webItemDesc);
        assertI18nString(templateNameI18nKey, templateName);
        assertI18nString(templateDescI18nKey, templateDesc);

        // TODO - Check the content of the generated content XML file


        // Check the content of the generated icon file
        // TODO - BAD! The icon should be specified in a CSS resource file! We should generate a stub for the CSS
        // selector that allows a) the default icon to be used if not specified b) the plugin dev to add a data-url.
    }

    private void assertAtlassianPluginXmlCorrect() throws Exception
    {
        // Check created <blueprint> element
        Element blueprintModule = getGeneratedModule();
        assertNodeText(blueprintModule, "@key", blueprintModuleKey);
        assertNodeText(blueprintModule, "@name", blueprintModuleName);
        assertNodeText(blueprintModule, "@index-key", blueprintIndexKey);
        assertNodeText(blueprintModule, "content-template/@ref", templateModuleKey);

        // Check created <content-template> element
        Element templateModule = getGeneratedModule("content-template");
        assertNodeText(templateModule, "@key", templateModuleKey);
        assertNodeText(templateModule, "@i18n-name-key", templateNameI18nKey);
        assertNodeText(templateModule, "description/@key", templateDescI18nKey);

        assertNodeText(templateModule, "resource/@name", templateResourceName);
        assertNodeText(templateModule, "resource/@type", templateResourceType);
        assertNodeText(templateModule, "resource/@location", templateResourceLocation);

        // Check created <web-item> element
        Element webItemModule = getGeneratedModule("web-item");
        assertNodeText(webItemModule, "@key", webItemModuleKey);
        assertNodeText(webItemModule, "@i18n-name-key", webItemNameI18nKey);
        assertNodeText(webItemModule, "@section", webItemSection);
        assertNodeText(webItemModule, "description/@key", webItemDescI18nKey);
        assertNodeText(webItemModule, "param/@name", WEB_ITEM_BLUEPRINT_KEY);
        assertNodeText(webItemModule, "param/@value", blueprintModuleKey);

        assertNodeText(webItemModule, "resource/@name", webItemResourceName);
        assertNodeText(webItemModule, "resource/@type", webItemResourceType);
        assertNodeText(webItemModule, "resource/@location", webItemResourceLocation);
    }

    private void assertNodeText(Element element, String nodePath, String expectedText)
    {
        assertEquals(expectedText, getText(element, nodePath));
    }

    private String getText(Element element, String nodePath)
    {
        return element.selectSingleNode(nodePath).getText();
    }

    // I prefer this method name - getI18nString doesn't indicate that an Assert is being done. dT
    private void assertI18nString(String i18nKey, String value) throws Exception
    {
        getI18nString(i18nKey, value);
    }

    private WebItemProperties makeWebItemProperties()
    {
        WebItemProperties webItem = new WebItemProperties();
        webItem.setModuleKey(webItemModuleKey);
        webItem.setNameI18nKey(webItemNameI18nKey);
        webItem.setModuleName(webItemName);
        webItem.setDescriptionI18nKey(webItemDescI18nKey);
        webItem.setDescription(webItemDesc);
        webItem.setSection(webItemSection);
        Resource webItemResource = new Resource();
        webItemResource.setName(webItemResourceName);
        webItemResource.setType(webItemResourceType);
        webItemResource.setLocation(webItemResourceLocation);
        List<Resource> resources = Lists.newArrayList(webItemResource);
        webItem.setResources(resources);
        webItem.addParam(WEB_ITEM_BLUEPRINT_KEY, blueprintModuleKey);
        return webItem;
    }

    private ContentTemplateProperties makeContentTemplateProperties()
    {
        // TODO - should the ContentTemplateProperties accept the plugin/package and attempt to generate the
        // i18n keys itself? If so, thta logic would be tested in the Properties object (or a "generator" helper for it).
        // TODO - should probably contact Jonathan Dok for this.
        ContentTemplateProperties template = new ContentTemplateProperties(templateModuleKey);
        template.setNameI18nKey(templateNameI18nKey);
        template.setModuleName(templateName);
        template.setDescriptionI18nKey(templateDescI18nKey);
        template.setDescription(templateDesc);
        Resource templateResource = new Resource();
        templateResource.setName(templateResourceName);
        templateResource.setType(templateResourceType);
        templateResource.setLocation(templateResourceLocation);
        template.addResource(templateResource);
        return template;
    }
}
