#!/bin/sh
# Determine the location of the script #

# resolve symbolic links
PRG="${0}"

while [ -h "${PRG}" ] ; do
  ls=`ls -ld "${PRG}"`
  link=`expr "${ls}" : '.*-> \(.*\)$'`
  if expr "${link}" : '/.*' > /dev/null; then
    PRG="${link}"
  else
    PRG=`dirname "${PRG}"`/"${link}"
  fi
done

PRGDIR=`dirname "${PRG}"`

echo "A new plugin structure is required for JIRA 5 plugins due to significant changes in the APIs."

while true; do
    echo "Create a plugin for?"
    echo "1) JIRA 5"
    echo "2) JIRA 4 (or earlier)"
    
    read n
    case $n in
        1) exec "${PRGDIR}/atlas-create-jira5-plugin" ; break;;
        2) exec "${PRGDIR}/atlas-create-jira4-plugin" ; break;;
    esac

done

