#!/bin/sh
#update file ownership/perms
for f in `find /usr/share/atlassian-plugin-sdk-${version}/bin/ -name "atlas-*"`; do
  chown root:root $f
  chmod 755 $f
done

for f in `find /usr/share/atlassian-plugin-sdk-${version}/apache-maven-${bundled.maven.version}/bin/ -name "*"`; do
  chown root:root $f
  chmod 755 $f
done

# Add the symlinks we need from /usr/share to /usr/bin
for f in `find /usr/bin/ -name "atlas-*"`; do
  chown root:root $f
done

echo "If you previously installed a version prior to version 4.0, you will need to remove all references to the atlassian-plugin-sdk directory from your PATH environment variable."

exit 0